name: audioexplorer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - aubio=0.4.9
  - librosa=0.6.3
  - pandas=0.25
  - numpy=1.17.0
  - xarray=0.11.3
  - joblib=0.13.2
  - matplotlib=3.1.1
  - scikit-learn=0.21.3
  - scipy=1.3.0
  - boto3=1.9.200
  - umap-learn=0.3.9
  - python-dotenv=0.10.3
  - click=7.0
  - datashader=0.7.0
  - flask=1.1.1
  - mkdocs=1.0.4
  - sqlalchemy=1.3.6
  - psycopg2=2.8.3
  - pip=19.2.1
  - markdown=3.1.1
  - testpath=0.3.1
  - PyYAML=5.1.2
  - hdf5=1.10.2
  - yaafe=0.70=py36h0bee7d0_1
  - pytables=3.4.4=py36ha205bf6_0
  - xgboost=0.90
  - s3fs=0.3.1
  - pip:
      - dash=1.1.1
      - dash_audio_components
      - dash_upload_components
      - sox
      - noisereduce
      - mkdocs-material
      - httpagentparser
      - ipinfo
      - simpleaudio