name: audioexplorer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - aubio=0.4.9
  - librosa=0.7.1
  - pandas=0.25.1
  - numpy=1.17.2
  - xarray=0.14
  - joblib=0.14
  - matplotlib=3.1.1
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - boto3=1.9.250
  - umap-learn=0.3.10
  - python-dotenv=0.10.3
  - click=7.0
  - datashader=0.8.0
  - flask=1.1.1
  - mkdocs=1.0.4
  - sqlalchemy=1.3.10
  - psycopg2=2.8.3
  - markdown=3.1.1
  - testpath=0.3.1
  - PyYAML=5.1.2
  - hdf5=1.10.2
  - yaafe=0.70=py36h0bee7d0_1
  - pytables=3.4.4=py36ha205bf6_0
  - xgboost=0.90
  - s3fs=0.3.5
  - pip=19.3
  - pip:
      - dash==1.4.1
      - dash_audio_components
      - dash_upload_components
      - sox==1.3.7
      - noisereduce==1.0.1
      - mkdocs-material==4.4.3
      - httpagentparser==1.9.0
      - ipinfo==2.1.0
      - simpleaudio==1.0.2