name: audioexplorer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - aubio=0.4.9
  - librosa=0.6.3
  - pandas=0.24.2
  - numpy=1.16.3
  - xarray=0.11.3
  - joblib=0.13.2
  - matplotlib=3.1.0
  - scikit-learn=0.21.2
  - scipy=1.3.0
  - boto3=1.9.155
  - umap-learn=0.3.8
  - python-dotenv=0.10.2
  - click=7.0
  - datashader=0.7.0
  - plotly=3.9.0
  - dash=0.43.0
  - dash-table=3.7.0
  - flask=1.0.3
  - mkdocs=1.0.4
  - sqlalchemy=1.3.3
  - psycopg2=2.8.2
  - pip=19.1.1
  - markdown=3.1
  - testpath=0.3.1
  - PyYAML<5
  - hdf5=1.10.2
  - yaafe=0.70=py36h0bee7d0_1
  - pytables=3.4.4=py36h5ca999c_0
  - pip:
    - awsebcli
    - dash_audio_components
    - dash_upload_components
    - sox
    - noisereduce
    - mkdocs-material
    - httpagentparser
    - ipinfo
    - simpleaudio
