name: audioexplorer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - aubio=0.4.9
  - librosa=0.7.2
  - pandas=1.0.1
  - numpy=1.18.1
  - xarray=0.15
  - joblib=0.14.1
  - matplotlib=3.1.3
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - boto3=1.12.4
  - umap-learn=0.3.10
  - python-dotenv=0.10.3
  - click=7.0
  - datashader=0.10.0
  - flask=1.1.1
  - mkdocs=1.0.4
  - sqlalchemy=1.3.10
  - psycopg2=2.8.3
  - markdown=3.2.1
  - testpath=0.3.1
  - PyYAML=5.1.2
  - hdf5=1.10.2
  - yaafe=0.70=py36h0bee7d0_1
  - pytables=3.4.4=py36ha205bf6_0
  - xgboost=0.90
  - s3fs=0.4.0
  - pip=20.0.2
  - pip:
      - dash==1.9.0
      - dash_audio_components
      - dash_upload_components
      - sox==1.3.7
      - noisereduce==1.0.1
      - mkdocs-material==4.6.3
      - httpagentparser==1.9.0
      - ipinfo==3.0.0
      - simpleaudio==1.0.2